Repository sainik-khaddar/Awesome-Portfolios, pull requests merged in 2022-10, with the labels that each got.

#4 supratick port
  supratick/mimi.css
  supratick/mimi.html
Labels: good first issue, hacktoberfest-accepted

#12 24_hrs clock
  24hrs_perfect/24_perfect.css
  24hrs_perfect/24_perfect.html
  timer/time.css
  timer/time.html
Labels: hacktoberfest-accepted

#22 Add files via upload
  ECELL TIMELINE/index.html
  ECELL TIMELINE/style.css
Labels: hacktoberfest-accepted, Good

#23 Add files via upload
  NOTES/stc 1.pdf
  NOTES/stc 3.pdf
  NOTES/stc 4.pdf
  NOTES/stc 5.pdf
  NOTES/stc2.pdf
Labels: hacktoberfest-accepted

#24 Add files via upload
  Apparatus IITBHU/ARTIK-10-dev-635x450.png
Labels: hacktoberfest-accepted

#25 Add files via upload
  CAMERA ACCESS/index.html
  CAMERA ACCESS/script.js
  CAMERA ACCESS/style.css
Labels: hacktoberfest-accepted
